adding DeVaucouleurs profile
DifferentiableUniverseInitiative/GalFlow pull request #16
Opened 2021-11-16 15:44 UTC by b-remy

Here is a small pull request adding DeVaucouleurs light profile so that we don't have to deal with sersic index and its normalizing factor, as suggested by @aguinot here: https://github.com/b-remy/gems/issues/1#issuecomment-934304200.

2021-11-19 11:28 UTC, b-remy commented
And also Exponential light profiles.

2021-11-20 13:46 UTC, EiffL requested changes
Looking good, only two small corrections that I could find

2021-11-20 13:46 UTC, EiffL commented on galflow/python/lightprofiles.py
> +  with tf.name_scope(name or "sersic"):
```suggestion
  with tf.name_scope(name or "exponential"):
```

2021-11-20 13:46 UTC, EiffL commented on galflow/python/lightprofiles.py
> +    >>> sersic(n=[2.], scale_radius=[5.], flux=[40.], nx=55)
```suggestion
    >>> exponential(scale_radius=[5.], flux=[40.], nx=55)
```

2021-11-20 14:00 UTC, merged

2021-11-20 14:00 UTC, EiffL approved these changes
LGTM